version: '3.4'

services:
  customers:
    image: julianhzd/ecommerceapicustomers:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"

  orders:
    image: julianhzd/ecommerceapiorders:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  products:
    image: julianhzd/ecommerceapiproducts:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80/http"


  search:
    image: julianhzd/ecommerceapisearch:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=https://ecommercehernandez.centralindia.cloudapp.azure.com:19081/Explorer/products/
      - Services__Customers=https://ecommercehernandez.centralindia.cloudapp.azure.com:19081/Explorer/customers/
      - Services__Orders=https://ecommercehernandez.centralindia.cloudapp.azure.com:19081/Explorer/orders/
    ports:
      - "6004:80"

